title: "Alex Carvalho"
author: "Alex Carvalho"
description: "A space where I share notes and insights on the subjects I'm studying."
avatar: "https://github.com/alex-carvalho.png"

github_username: "alex-carvalho"
linkedin_username: "alex-carvalho-ac"

navigation:
  - title: "Latest"
    url: "/"
  - title: "Archive"
    url: "/archive.html"
  - title: "About"
    url: "/about/"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: false # enabled to let Jekyll/Rouge highlight code blocks
    
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      tags: Other
